const properties = [
  {
    title: "Loft above the old print works",
    description:
      "A character-filled loft tucked above a restored old print works in Porto. Original details, warm interiors, and plenty of space for a relaxed city stay.",
    location: {
      city: "Porto",
      country: "Portugal",
      address: "Rua de Cedofeita, Porto, Portugal",
    },
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop",
    ],
    price: 143,
    type: "Unique stay",
    rating: 4.93,
    reviews: 212,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Kitchen", "Workspace", "Washer"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: false,
      wideDoorways: false,
    },
    hostStatus: "Superhost",
    vibe: "host makes bread",
    mapPosition: {
      top: "20%",
      left: "40%",
    },
  },
  {
    title: "Traditional Machiya in Historic Gion",
    description:
      "Immerse yourself in Kyoto's rich history in this restored traditional wooden townhouse. Features private tatami rooms, a serene inner zen garden, and cedar bath tub.",
    location: {
      city: "Kyoto",
      country: "Japan",
      address: "Gion-machi, Higashiyama, Kyoto, Japan",
    },
    images: [
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&auto=format&fit=crop",
    ],
    price: 265,
    type: "Unique stay",
    rating: 4.98,
    reviews: 142,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Kitchen", "Workspace", "Air conditioning"],
    bookingOptions: {
      instantBook: false,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: true,
      wideDoorways: false,
    },
    hostStatus: "Superhost",
    vibe: "zen tranquility",
    mapPosition: {
      top: "25%",
      left: "70%",
    },
  },
  {
    title: "Cliffside Glass Cabin with Northern Lights View",
    description:
      "Modern glass-walled cabin surrounded by rugged volcanic landscapes. Watch the Aurora Borealis directly from your bed or the private geothermal hot tub.",
    location: {
      city: "Vik",
      country: "Iceland",
      address: "Suðurland, Vik, Iceland",
    },
    images: [
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop",
    ],
    price: 380,
    type: "Unique stay",
    rating: 4.96,
    reviews: 95,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Parking", "Hot tub", "Heating"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: true,
      wideDoorways: true,
    },
    hostStatus: "Superhost",
    vibe: "stargazer paradise",
    mapPosition: {
      top: "15%",
      left: "35%",
    },
  },
  {
    title: "Sun-Drenched Villa Overlooking the Tyrrhenian Sea",
    description:
      "Perched high on Positano’s cliffside with sweeping ocean vistas, private lemon groves, and classic Mediterranean tilework throughout.",
    location: {
      city: "Positano",
      country: "Italy",
      address: "Via Cristoforo Colombo, Positano, Italy",
    },
    images: [
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop",
    ],
    price: 490,
    type: "Entire home",
    rating: 4.91,
    reviews: 178,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Kitchen", "Pool", "Balcony", "Air conditioning"],
    bookingOptions: {
      instantBook: false,
      selfCheckIn: false,
    },
    accessibility: {
      stepFreeEntrance: false,
      wideDoorways: false,
    },
    hostStatus: "Superhost",
    vibe: "dolce far niente",
    mapPosition: {
      top: "40%",
      left: "50%",
    },
  },
  {
    title: "Eco Bamboo Villa in the Jungle Canopy",
    description:
      "An open-air architectural masterpiece built entirely of bamboo. Overlooks lush jungle foliage and a winding river in the heart of Sidemen.",
    location: {
      city: "Bali",
      country: "Indonesia",
      address: "Sidemen, Karangasem, Bali, Indonesia",
    },
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?w=800&auto=format&fit=crop",
    ],
    price: 210,
    type: "Unique stay",
    rating: 4.95,
    reviews: 310,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Pool", "Free breakfast", "Parking"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: false,
      wideDoorways: false,
    },
    hostStatus: "Superhost",
    vibe: "jungle sanctuary",
    mapPosition: {
      top: "65%",
      left: "80%",
    },
  },
  {
    title: "Luxury Modern Penthouse with Eiffel Tower Views",
    description:
      "Sophisticated Parisian apartment featuring herringbone parquet floors, marble fireplaces, and an expansive balcony framing the Eiffel Tower.",
    location: {
      city: "Paris",
      country: "France",
      address: "Avenue Montaigne, 75008 Paris, France",
    },
    images: [
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop",
    ],
    price: 520,
    type: "Entire home",
    rating: 4.88,
    reviews: 84,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Kitchen", "Elevator", "Workspace", "Washer"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: true,
      wideDoorways: true,
    },
    hostStatus: "Regular",
    vibe: "parisian chic",
    mapPosition: {
      top: "30%",
      left: "45%",
    },
  },
  {
    title: "Authentic Riad with Rooftop Pool & Courtyard",
    description:
      "A serene Moroccan haven in the heart of the Medina. Hand-crafted zellige tiles, central fountain courtyard, and a panoramic roof terrace.",
    location: {
      city: "Marrakech",
      country: "Morocco",
      address: "Derb Dabachi, Medina, Marrakech, Morocco",
    },
    images: [
      "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop",
    ],
    price: 185,
    type: "Boutique hotel",
    rating: 4.97,
    reviews: 165,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Pool", "Air conditioning", "Free breakfast"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: false,
    },
    accessibility: {
      stepFreeEntrance: true,
      wideDoorways: false,
    },
    hostStatus: "Superhost",
    vibe: "mint tea magic",
    mapPosition: {
      top: "48%",
      left: "38%",
    },
  },
  {
    title: "Mid-Century Modern Villa in Joshua Tree",
    description:
      "Secluded desert retreat blending sleek 1960s design with stark natural beauty. Includes a cowboy soaking tub, fire pit, and outdoor vinyl station.",
    location: {
      city: "Joshua Tree",
      country: "United States",
      address: "Park Boulevard, Joshua Tree, CA, USA",
    },
    images: [
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop",
    ],
    price: 310,
    type: "Entire home",
    rating: 4.94,
    reviews: 230,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Kitchen", "Parking", "Hot tub", "Air conditioning"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: true,
      wideDoorways: true,
    },
    hostStatus: "Superhost",
    vibe: "desert stargazing",
    mapPosition: {
      top: "38%",
      left: "18%",
    },
  },
  {
    title: "High-Rise Studio with Tokyo Tower Panorama",
    description:
      "Sleek and hyper-functional studio apartment in Roppongi. floor-to-ceiling glass offering unmatched night views of Tokyo's neon skyline.",
    location: {
      city: "Tokyo",
      country: "Japan",
      address: "Roppongi, Minato-ku, Tokyo, Japan",
    },
    images: [
      "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop",
    ],
    price: 175,
    type: "Private room",
    rating: 4.87,
    reviews: 112,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Workspace", "Elevator", "Washer", "Air conditioning"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: true,
      wideDoorways: true,
    },
    hostStatus: "Regular",
    vibe: "cyberpunk skyline",
    mapPosition: {
      top: "28%",
      left: "82%",
    },
  },
  {
    title: "Glass Igloo & Luxury Chalet in Lapland",
    description:
      "Experience the Arctic wilderness in total comfort. Private heated glass dome for watching the night sky, attached to a luxury pine wood cabin.",
    location: {
      city: "Rovaniemi",
      country: "Finland",
      address: "Arctic Circle, Rovaniemi, Finland",
    },
    images: [
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop",
    ],
    price: 450,
    type: "Unique stay",
    rating: 4.99,
    reviews: 87,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Heating", "Sauna", "Parking"],
    bookingOptions: {
      instantBook: false,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: true,
      wideDoorways: false,
    },
    hostStatus: "Superhost",
    vibe: "winter wonderland",
    mapPosition: {
      top: "10%",
      left: "52%",
    },
  },
  {
    title: "Boho Beachfront Loft with Ocean Balcony",
    description:
      "Step right out onto the sands of Ipanema Beach. Vibrant coastal decor, floor-to-ceiling sliding glass doors, and effortless seaside living.",
    location: {
      city: "Rio de Janeiro",
      country: "Brazil",
      address: "Av. Vieira Souto, Ipanema, Rio de Janeiro, Brazil",
    },
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&auto=format&fit=crop",
    ],
    price: 220,
    type: "Entire home",
    rating: 4.89,
    reviews: 156,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Kitchen", "Air conditioning", "Elevator"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: true,
      wideDoorways: true,
    },
    hostStatus: "Superhost",
    vibe: "samba sunset",
    mapPosition: {
      top: "72%",
      left: "32%",
    },
  },
  {
    title: "Alpine Chalet with Panoramic Matterhorn View",
    description:
      "A cozy, timber-crafted Swiss cabin featuring a roaring fireplace, private Scandinavian sauna, and front-row seats to the Matterhorn peak.",
    location: {
      city: "Zermatt",
      country: "Switzerland",
      address: "Steinmattstrasse, Zermatt, Switzerland",
    },
    images: [
      "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop",
    ],
    price: 410,
    type: "Entire home",
    rating: 4.97,
    reviews: 104,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Kitchen", "Heating", "Workspace", "Washer"],
    bookingOptions: {
      instantBook: false,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: false,
      wideDoorways: false,
    },
    hostStatus: "Superhost",
    vibe: "cozy hot cocoa",
    mapPosition: {
      top: "35%",
      left: "48%",
    },
  },
  {
    title: "Fjordfront Cabin on Water's Edge",
    description:
      "Listen to the quiet water lap against the stilts of this historic red fisherman's cabin (Rorbu) in the heart of the Lofoten islands.",
    location: {
      city: "Reine",
      country: "Norway",
      address: "Reinefjorden, Lofoten, Norway",
    },
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop",
    ],
    price: 295,
    type: "Unique stay",
    rating: 4.94,
    reviews: 121,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Kitchen", "Parking", "Heating"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: false,
      wideDoorways: false,
    },
    hostStatus: "Superhost",
    vibe: "pure silence",
    mapPosition: {
      top: "12%",
      left: "48%",
    },
  },
  {
    title: "Historic Canal House Suite",
    description:
      "Charming suite in a 17th-century canal house with exposed beams, large sash windows, and serene views over the Prinsengracht waterway.",
    location: {
      city: "Amsterdam",
      country: "Netherlands",
      address: "Prinsengracht, Amsterdam, Netherlands",
    },
    images: [
      "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop",
    ],
    price: 240,
    type: "Boutique hotel",
    rating: 4.9,
    reviews: 189,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Workspace", "Heating"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: false,
    },
    accessibility: {
      stepFreeEntrance: false,
      wideDoorways: false,
    },
    hostStatus: "Regular",
    vibe: "bicycles and espresso",
    mapPosition: {
      top: "22%",
      left: "46%",
    },
  },
  {
    title: "Luxury Safari Tent over Wildlife Sanctuary",
    description:
      "Canvas glamping lodge set elevated above the wild savannah. Frequent visits from giraffes and zebras right outside your private deck.",
    location: {
      city: "Nairobi",
      country: "Kenya",
      address: "Langata, Nairobi, Kenya",
    },
    images: [
      "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&auto=format&fit=crop",
    ],
    price: 360,
    type: "Unique stay",
    rating: 4.97,
    reviews: 73,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Parking", "Free breakfast"],
    bookingOptions: {
      instantBook: false,
      selfCheckIn: false,
    },
    accessibility: {
      stepFreeEntrance: true,
      wideDoorways: true,
    },
    hostStatus: "Superhost",
    vibe: "out of africa",
    mapPosition: {
      top: "58%",
      left: "58%",
    },
  },
  {
    title: "Architectural Cave Suite with Sunset Terrace",
    description:
      "Traditional Caldera cave house carved into the cliffs of Oia. Minimalist whitewashed interiors and a private plunge pool over the Aegean.",
    location: {
      city: "Santorini",
      country: "Greece",
      address: "Oia Cliffside, Santorini, Greece",
    },
    images: [
      "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&auto=format&fit=crop",
    ],
    price: 430,
    type: "Unique stay",
    rating: 4.95,
    reviews: 260,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Pool", "Air conditioning", "Free breakfast"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: false,
      wideDoorways: false,
    },
    hostStatus: "Superhost",
    vibe: "postcard living",
    mapPosition: {
      top: "42%",
      left: "52%",
    },
  },
  {
    title: "Secluded Treehouse in Rain Forest Canopy",
    description:
      "Nestled 30 feet above the forest floor, surrounded by sloths and toucans. Built from sustainable teakwood with high-speed satellite Wi-Fi.",
    location: {
      city: "Monteverde",
      country: "Costa Rica",
      address: "Santa Elena, Monteverde, Costa Rica",
    },
    images: [
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&auto=format&fit=crop",
    ],
    price: 190,
    type: "Unique stay",
    rating: 4.92,
    reviews: 148,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Kitchen", "Parking"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: false,
      wideDoorways: false,
    },
    hostStatus: "Superhost",
    vibe: "pura vida",
    mapPosition: {
      top: "52%",
      left: "22%",
    },
  },
  {
    title: "Heritage Art Deco Room in South Beach",
    description:
      "Bright room inside an iconic 1930s hotel on Ocean Drive. Pastel aesthetics, rooftop lounge access, and steps from the white sand beaches.",
    location: {
      city: "Miami",
      country: "United States",
      address: "Ocean Drive, Miami Beach, FL, USA",
    },
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop",
    ],
    price: 160,
    type: "Private room",
    rating: 4.81,
    reviews: 98,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Pool", "Air conditioning", "Elevator"],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: true,
      wideDoorways: true,
    },
    hostStatus: "Regular",
    vibe: "neon palm trees",
    mapPosition: {
      top: "45%",
      left: "24%",
    },
  },
  {
    title: "Restored Stone Cottage in the Highlands",
    description:
      "Rugged 18th-century croft surrounded by rolling green hills and misty lochs. Cozy interior equipped with wood-burning stove and deep soaking tub.",
    location: {
      city: "Isle of Skye",
      country: "United Kingdom",
      address: "Portree, Isle of Skye, Scotland, UK",
    },
    images: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?w=800&auto=format&fit=crop",
    ],
    price: 205,
    type: "Entire home",
    rating: 4.96,
    reviews: 114,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Kitchen", "Parking", "Heating", "Washer"],
    bookingOptions: {
      instantBook: false,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: true,
      wideDoorways: false,
    },
    hostStatus: "Superhost",
    vibe: "misty retreat",
    mapPosition: {
      top: "18%",
      left: "42%",
    },
  },
  {
    title: "Harbourside Designer Apartment in Opera Quays",
    description:
      "Modern luxury apartment featuring uninterrupted views of the Sydney Harbour Bridge and Opera House. Walkable to world-class dining.",
    location: {
      city: "Sydney",
      country: "Australia",
      address: "Circular Quay, Sydney, NSW, Australia",
    },
    images: [
      "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop",
    ],
    price: 340,
    type: "Entire home",
    rating: 4.91,
    reviews: 137,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: [
      "Wi-Fi",
      "Kitchen",
      "Workspace",
      "Air conditioning",
      "Elevator",
    ],
    bookingOptions: {
      instantBook: true,
      selfCheckIn: true,
    },
    accessibility: {
      stepFreeEntrance: true,
      wideDoorways: true,
    },
    hostStatus: "Superhost",
    vibe: "harbour glow",
    mapPosition: {
      top: "80%",
      left: "88%",
    },
  },
];

module.exports = properties;
